### ISSUE TITLE
Hangs on looking for receivers. 

### ISSUE THREAD

**Issue by vukosim** [boombatower/chromecast-dashboard#1]
Whitelisted and the cast to tab actually says click on cast for better experience. So odd its not seeing receivers.

**Comment by boombatower** [comment]
If you open console in Chrome, do you see any interesting messages?

**Comment by boombatower** [comment]
please re-open with details

**Comment by apeckham** [comment]
Whitelisted and same problem here. No lines appear in Chrome console on sender, and nothing relevant on chromecast:9222/devtools/devtools.html... breakpoint shows that onReceiverList in main.js is getting called once with an empty array.
