### ISSUE TITLE
Cannot read property 'requestSession' of undefined

### ISSUE THREAD

**Issue by nkuznetsow** [boombatower/chromecast-dashboard#12]
The Chromecast Dashboard stop working in last chrome version.

I have chrome v. 72.0.3626.119 (64 bit) running on windows 7 SP 1. Since update to this Google Chrome version Chromecast dashboard stops working.

I have follow message in developer console when I click "Launch": 

```
Uncaught TypeError: Cannot read property 'requestSession' of undefined
    at sendMessage (main.js:68)
    at connect (main.js:82)
    at <anonymous>:1:1
sendMessage @ main.js:68
connect @ main.js:82
(anonymous) @ VM37:1
```

**Comment by boombatower** [comment]
Assume this is related to #11 and should have probably been posted as an update to that issue. The code in question:

https://github.com/boombatower/chromecast-dashboard/blob/40c7d2619b04744a63d98e7b1f731c5d9def9cd9/sender/main.js#L68-L72

`chrome.cast.requestSession` means that `chome.cast` is `undefined`. That is outside the scope of this project as it is provided by chrome itself. I verified this on the same version on Linux and it works just fine. Please verify other sites can cast properly as I would suspect they do not.

**Comment by nkuznetsow** [comment]
I have checked Chromecast button on YouTube it is working fine.  In same time, chromecast-dashboard cause an Exception in console.

**Comment by boombatower** [comment]
Need to use the [sender site in https](https://boombatower.github.io/chromecast-dashboard/sender/). I switched the github pages site to force https although all the links in the repo are already https. Chrome (tm).
