### ISSUE TITLE
"Cast SDK Additional Subdomains" no longer an option

### ISSUE THREAD

**Issue by bchecketts** [boombatower/chromecast-dashboard#2]
Looks as though the ChromeCast extension has probably changed and "Cast SDK Additional Subdomains" is no longer an available option.  I'm not able to get anything to work, likely due to that.

**Comment by hlenke** [comment]
+1 Same here.

**Comment by harperreed** [comment]
any suggested fix here?

**Comment by boombatower** [comment]
not sure, seems like chromecast would need to provide something equivalent.

**Comment by rmm5t** [comment]
I went looking for something like this project earlier today. I was pretty stoked to find it, and it even prompted me to order a chromecast, but does this Issue imply that this application is no longer functional with the Chromecast?

**Comment by boombatower** [comment]
It seems one must now re-register for an app key and pay $5. Possibly also tweak for SDK changes. I'll take a look at doing so, but assuming no sdk changes I imagine it'd work with your own developer key.

**Comment by boombatower** [comment]
I went ahead and started application process. I assume there should be no problems, especially since I was registered before they made a big ordeal out of it.

**Comment by boombatower** [comment]
looks like they semi-needlessly change all the method names and what not. hmm. I'll work on updating, but their documentation is rather pathetic.

**Comment by boombatower** [comment]
Finally got around to updating this. 2.0.0 release created.

**Comment by boombatower** [comment]
Would be nice if they had provided some migration documentation, was quite a bit of work.

8141113d1543ba2a70c0ea6d2e72ceeca6a700d1

**Comment by rmm5t** [comment]
@boombatower I really appreciate your work on this. I actually looked into building something similar with the new version of the API, but the Google docs seemed lacking and/or confusing, and I went on to other things. I'm really grateful that you stepped up to remedy this. Now, I just have to figure out how to get it to work on my new Chromecast. :beers:

**Comment by boombatower** [comment]
I completely agree with your comments about the docs.
