### ISSUE TITLE
Black page showing on Chromecast

### ISSUE THREAD

**Issue by ulfjack** [boombatower/chromecast-dashboard#3]
I tried running it, and it just shows a black screen on the Chromecast device - no error message, no nothing. It looks like the reason for that is that the default refresh time is set to 0. If I change it to something else, it seems to work.

**Comment by boombatower** [comment]
Hmm, zero should work and does for me. Could you try some different URLs to see if something particular?

**Comment by ulfjack** [comment]
I'm looking into it again today.

Here's my theory of what happened - the initial page I used had black text on the default background, and for some reason, the default background on the device is black, so the page ended up rendering completely black.

I'm observing a different issue right now, which is that it doesn't reload the page from the server (which could be an issue with the server; I don't know yet).

**Comment by ulfjack** [comment]
I rebooted the Chromecast and now I can't reproduce the earlier reload problem.
