### ISSUE TITLE
Clear cache?

### ISSUE THREAD

**Issue by stellanhaglund** [boombatower/chromecast-dashboard#5]
Is there a way to clear cache for the application, i'm doing some changes on the dashboard I'm going to show but it's not reflected on the screen even if I reload everything.

**Comment by boombatower** [comment]
The cache is not controlled by the chromecast-dashboard receiver, but instead by Chrome like on desktop. Google "chromecast clear cache" results in some useful resutls such as: http://stackoverflow.com/questions/19019853/chromecast-how-to-clear-receiver-cache.

Hope that helps.
