### ISSUE TITLE
Does it "refresh" the website periodically?

### ISSUE THREAD

**Issue by marksev1** [boombatower/chromecast-dashboard#7]
If there is a website which has sensor values on it (lets say home-assistant dashboard or node-red dashboard or graphana or something), does it refresh the sensor values on it?

**Comment by boombatower** [comment]
If the web page refreshes them it will be no different on the chromecast, otherwise you can see in the launcher it has a refresh option which is the number of second to wait before reloading the whole page.

**Comment by marksev1** [comment]
Thanks! Cool!
